import { Banknote, Plus, ReceiptText, Trash2, TrendingUp } from "lucide-react";
import type { Metadata } from "next";
import { AdminShell } from "@/components/admin-shell";
import { requireAdminSession } from "@/lib/admin-auth";
import { brusselsLocalToUtc, formatMoney } from "@/lib/admin-booking";
import { addUtcDays, dateOnly } from "@/lib/availability";
import { prisma } from "@/lib/prisma";
import { addBusinessCost, deleteBusinessCost } from "./actions";

export const metadata: Metadata = { title: "Revenue and costs", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
const categories = ["TRANSPORT", "PRODUCTS", "EQUIPMENT", "SUBSCRIPTIONS", "OTHER"] as const;
function localDate(date = new Date()) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Brussels", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
function periodStarts() { const today = dateOnly(localDate()); const week = new Date(today); const day = week.getUTCDay() || 7; week.setUTCDate(week.getUTCDate() - day + 1); const month = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1)); const year = new Date(Date.UTC(today.getUTCFullYear(), 0, 1)); return { today, week, month, year, tomorrow: addUtcDays(today, 1) }; }
function monthKey(date: Date, zone?: string) { return new Intl.DateTimeFormat("en-CA", { ...(zone ? { timeZone: zone } : { timeZone: "UTC" }), year: "numeric", month: "2-digit" }).format(date); }

export default async function FinancePage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) {
  const [user, query] = await Promise.all([requireAdminSession(), searchParams]); const starts = periodStarts(); const now = new Date(); const nextYear = new Date(Date.UTC(starts.year.getUTCFullYear() + 1, 0, 1));
  const trendStart = new Date(Date.UTC(starts.month.getUTCFullYear(), starts.month.getUTCMonth() - 11, 1));
  const [paid, costs, recentCosts] = await Promise.all([
    prisma.booking.findMany({ where: { paymentStatus: "PAID", paidAt: { not: null, gte: brusselsLocalToUtc(trendStart.toISOString().slice(0, 10), "00:00") ?? trendStart } }, select: { paidAt: true, finalPrice: true, estimatedPrice: true, service: { select: { name: true } } } }),
    prisma.businessCost.findMany({ where: { incurredOn: { gte: trendStart, lt: nextYear } }, orderBy: { incurredOn: "asc" } }),
    prisma.businessCost.findMany({ orderBy: [{ incurredOn: "desc" }, { createdAt: "desc" }], take: 30 }),
  ]);
  const revenueValue = (booking: (typeof paid)[number]) => Number(booking.finalPrice ?? booking.estimatedPrice ?? 0);
  const ranges = [{ label: "Today", start: starts.today, end: starts.tomorrow }, { label: "This week", start: starts.week, end: starts.tomorrow }, { label: "This month", start: starts.month, end: starts.tomorrow }, { label: "This year", start: starts.year, end: nextYear }];
  const summaries = ranges.map((range) => { const startAt = brusselsLocalToUtc(range.start.toISOString().slice(0, 10), "00:00") ?? range.start; const endAt = brusselsLocalToUtc(range.end.toISOString().slice(0, 10), "00:00") ?? range.end; const revenue = paid.filter((item) => item.paidAt && item.paidAt >= startAt && item.paidAt < endAt).reduce((sum, item) => sum + revenueValue(item), 0); const cost = costs.filter((item) => item.incurredOn >= range.start && item.incurredOn < range.end).reduce((sum, item) => sum + Number(item.amount), 0); return { ...range, revenue, cost, net: revenue - cost }; });
  const months = Array.from({ length: 12 }, (_, index) => new Date(Date.UTC(starts.month.getUTCFullYear(), starts.month.getUTCMonth() - 11 + index, 1))).map((date) => { const key = monthKey(date); const revenue = paid.filter((item) => item.paidAt && monthKey(item.paidAt, "Europe/Brussels") === key).reduce((sum, item) => sum + revenueValue(item), 0); const cost = costs.filter((item) => monthKey(item.incurredOn) === key).reduce((sum, item) => sum + Number(item.amount), 0); return { key, label: date.toLocaleDateString("en-BE", { month: "short", year: "2-digit", timeZone: "UTC" }), revenue, cost, net: revenue - cost }; });
  const maxTrend = Math.max(1, ...months.flatMap((month) => [month.revenue, month.cost])); const serviceRevenue = Object.entries(paid.reduce<Record<string, number>>((map, item) => ({ ...map, [item.service.name]: (map[item.service.name] ?? 0) + revenueValue(item) }), {})).sort((a, b) => b[1] - a[1]);
  return <AdminShell email={user.email ?? "owner"}><div className="admin-content"><div className="admin-page-heading"><div><p className="eyebrow">Financial performance</p><h1>Revenue and costs</h1><p>Track cash in, operating expenses and net performance over time.</p></div></div>
    {query.error ? <div className="form-alert" role="alert">{query.error}</div> : null}{query.saved ? <div className="admin-success">Business cost added.</div> : null}{query.deleted ? <div className="admin-success">Business cost removed.</div> : null}
    <section aria-label="Financial summary" className="finance-metrics">{summaries.map((item) => <article key={item.label}><span>{item.label}</span><div><small>Revenue</small><strong>{formatMoney(item.revenue)}</strong></div><div><small>Costs</small><b>{formatMoney(item.cost)}</b></div><div data-negative={item.net < 0}><small>Net</small><b>{formatMoney(item.net)}</b></div></article>)}</section>
    <section className="finance-workspace"><div className="finance-analysis"><div className="admin-section-title"><h2>12-month trend</h2><TrendingUp aria-hidden="true" size={20} /></div><div className="finance-chart">{months.map((month) => <div className="finance-chart-row" key={month.key}><span>{month.label}</span><div><i style={{ width: `${month.revenue / maxTrend * 100}%` }} /><em style={{ width: `${month.cost / maxTrend * 100}%` }} /></div><b>{formatMoney(month.net)}</b></div>)}</div><div className="finance-legend"><span><i />Revenue</span><span><i />Costs</span></div><div className="admin-section-title"><h2>Revenue by service</h2><Banknote aria-hidden="true" size={20} /></div><div className="service-revenue">{serviceRevenue.length ? serviceRevenue.map(([name, value]) => <div key={name}><span>{name}</span><strong>{formatMoney(value)}</strong></div>) : <p>No paid revenue yet.</p>}</div></div>
      <aside className="cost-entry"><div className="admin-section-title"><h2>Add business cost</h2><Plus aria-hidden="true" size={20} /></div><form action={addBusinessCost} className="admin-update-form"><label className="form-field">Date<input defaultValue={localDate(now)} name="incurredOn" required type="date" /></label><label className="form-field">Category<select name="category">{categories.map((category) => <option key={category} value={category}>{category.toLowerCase().replaceAll("_", " ")}</option>)}</select></label><label className="form-field">Description<input name="description" placeholder="e.g. Interior cleaner" required /></label><label className="form-field">Amount (€)<input min="0.01" name="amount" required step="0.01" type="number" /></label><label className="form-field">Notes<textarea name="notes" rows={3} /></label><button className="button button-primary" type="submit"><ReceiptText aria-hidden="true" size={18} />Add cost</button></form></aside>
    </section><section className="recent-costs"><div className="admin-section-title"><h2>Recent costs</h2><span>{recentCosts.length} shown</span></div>{recentCosts.length ? <div>{recentCosts.map((cost) => <article key={cost.id}><div><strong>{cost.description}</strong><span>{cost.category.toLowerCase().replaceAll("_", " ")} · {cost.incurredOn.toLocaleDateString("en-BE", { dateStyle: "medium", timeZone: "UTC" })}</span></div><b>{formatMoney(cost.amount)}</b><form action={deleteBusinessCost}><input name="id" type="hidden" value={cost.id} /><button aria-label={`Delete ${cost.description}`} title="Delete cost" type="submit"><Trash2 aria-hidden="true" size={16} /></button></form></article>)}</div> : <p>No business costs recorded yet.</p>}</section>
  </div></AdminShell>;
}
