import { ArrowLeft, CalendarClock, Mail, MapPin, MessageCircle, Phone, Save, ShieldCheck } from "lucide-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { updateBooking } from "@/app/admin/actions";
import { StatusBadge } from "@/components/admin-booking-ui";
import { AdminShell } from "@/components/admin-shell";
import { requireAdminSession } from "@/lib/admin-auth";
import { formatMoney } from "@/lib/admin-booking";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Booking details", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

function localInputParts(value: Date | null) {
  if (!value) return { date: "", time: "" };
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Brussels", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(value);
  const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "";
  return { date: `${get("year")}-${get("month")}-${get("day")}`, time: `${get("hour")}:${get("minute")}` };
}

function timelineValue(value: string | null) { return value ? value.replaceAll("_", " ") : "Not set"; }

export default async function AdminBookingDetail({ params, searchParams }: { params: Promise<{ reference: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [user, { reference }, feedback] = await Promise.all([requireAdminSession(), params, searchParams]);
  const booking = await prisma.booking.findUnique({ where: { publicReference: reference }, include: { service: true, addOns: { include: { addOn: true } }, statusHistory: { orderBy: { createdAt: "desc" } }, auditLog: { orderBy: { createdAt: "desc" }, take: 30 } } });
  if (!booking) notFound();
  const appointment = localInputParts(booking.appointmentStartAt);
  const whatsappText = encodeURIComponent(`Hello ${booking.customerName}, your Life's Details ${booking.service.name} booking ${booking.publicReference} is ready to confirm. Please reply to acknowledge the appointment details.`);
  const whatsappPhone = booking.phone.replace(/\D/g, "").replace(/^0/, "32");

  return <AdminShell email={user.email ?? "owner"}><div className="admin-content admin-detail"><Link className="admin-back" href="/admin"><ArrowLeft aria-hidden="true" size={18} />Back to bookings</Link><div className="admin-detail-heading"><div><div className="admin-heading-meta"><StatusBadge status={booking.status} /><code>{booking.publicReference}</code></div><h1>{booking.customerName}</h1><p>{booking.service.name} for {booking.vehicleMake} {booking.vehicleModel}</p></div><div className="admin-contact-actions"><a className="button button-secondary" href={`tel:${booking.phone}`}><Phone aria-hidden="true" size={18} />Call</a><a className="button button-secondary" href={`mailto:${booking.email}`}><Mail aria-hidden="true" size={18} />Email</a><a className="button button-primary" href={`https://wa.me/${whatsappPhone}?text=${whatsappText}`} rel="noreferrer" target="_blank"><MessageCircle aria-hidden="true" size={18} />WhatsApp</a></div></div>
    {feedback.saved ? <p className="admin-success" role="status"><ShieldCheck aria-hidden="true" size={18} />Booking changes saved and audited.</p> : null}{feedback.error ? <p className="form-alert" role="alert">{feedback.error}</p> : null}
    <div className="admin-detail-grid"><div className="admin-detail-main"><section className="admin-panel"><h2>Booking facts</h2><dl className="admin-facts"><div><dt>Customer</dt><dd>{booking.customerName}<small>{booking.email}<br />{booking.phone} · prefers {booking.preferredContactMethod.toLowerCase()}</small></dd></div><div><dt>Vehicle</dt><dd>{booking.vehicleMake} {booking.vehicleModel}<small>{booking.vehicleType.replaceAll("-", " ")} · {booking.vehicleCondition.toLowerCase()} condition{booking.vehicleColour ? ` · ${booking.vehicleColour}` : ""}{booking.licencePlateOptional ? ` · ${booking.licencePlateOptional}` : ""}</small></dd></div><div><dt>Service</dt><dd>{booking.service.name}<small>{booking.addOns.length ? booking.addOns.map(({ addOn }) => addOn.name).join(", ") : "No add-ons"} · estimate {formatMoney(booking.estimatedPrice)}</small></dd></div><div><dt>Requested time</dt><dd>{booking.preferredDate.toLocaleDateString("en-BE", { dateStyle: "long", timeZone: "UTC" })}<small>{booking.preferredTimeWindow.toLowerCase()}{booking.alternativeDate ? ` · alternative ${booking.alternativeDate.toLocaleDateString("en-BE", { dateStyle: "medium", timeZone: "UTC" })}` : ""}</small></dd></div><div><dt>Location</dt><dd>{booking.addressLine}, {booking.postcode} {booking.city}<small>{booking.serviceLocationType.toLowerCase()} · water {booking.accessToWater ? "yes" : "no"} · electricity {booking.accessToElectricity ? "yes" : "no"}</small><a href={`https://www.openstreetmap.org/search?query=${encodeURIComponent(`${booking.addressLine}, ${booking.postcode} ${booking.city}`)}`} rel="noreferrer" target="_blank"><MapPin aria-hidden="true" size={15} />Open map</a></dd></div><div><dt>Condition</dt><dd>{[booking.hasPetHair && "Pet hair", booking.hasStains && "Stains", booking.hasStrongOdour && "Strong odour"].filter(Boolean).join(", ") || "No condition flags"}<small>{booking.conditionNotes || "No customer notes"}</small></dd></div><div><dt>Source</dt><dd>{booking.acquisitionSource || "Not provided"}<small>Consent recorded {booking.consentAt.toLocaleDateString("en-BE")} · marketing {booking.marketingConsent ? "yes" : "no"}</small></dd></div></dl></section>
      <section className="admin-panel"><h2>History</h2><ol className="admin-timeline">{booking.statusHistory.map((item) => <li key={item.id}><span /><div><strong>{timelineValue(item.fromStatus)} → {timelineValue(item.toStatus)}</strong><small>{item.createdAt.toLocaleString("en-BE", { timeZone: "Europe/Brussels" })}</small><p>{item.note || "Status updated."}</p></div></li>)}{booking.auditLog.map((item) => <li key={item.id}><span /><div><strong>{item.field?.replaceAll(/([A-Z])/g, " $1") ?? item.action}</strong><small>{item.createdAt.toLocaleString("en-BE", { timeZone: "Europe/Brussels" })} · {item.actorEmail}</small><p>{timelineValue(item.fromValue)} → {timelineValue(item.toValue)}{item.note ? ` · ${item.note}` : ""}</p></div></li>)}</ol></section></div>
      <aside className="admin-panel admin-action-panel"><div><p className="eyebrow">Owner actions</p><h2>Update booking</h2></div><form action={updateBooking} className="admin-update-form"><input name="bookingId" type="hidden" value={booking.id} /><input name="reference" type="hidden" value={booking.publicReference} /><label className="form-field">Status<select defaultValue={booking.status} name="status"><option value="REQUESTED">New request</option><option value="REVIEWING">Reviewing</option><option value="CONFIRMED">Confirmed</option><option value="RESCHEDULE_REQUIRED">Needs new date</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option><option value="NO_SHOW">No-show</option></select></label><div className="form-grid two-columns"><label className="form-field">Appointment date<input defaultValue={appointment.date} name="appointmentDate" type="date" /></label><label className="form-field">Start time<input defaultValue={appointment.time} name="appointmentTime" type="time" /></label></div><p className="admin-form-note"><CalendarClock aria-hidden="true" size={15} />End time follows the service duration ({booking.service.estimatedDurationMinutes} minutes).</p><div className="form-grid two-columns"><label className="form-field">Estimate (€)<input defaultValue={booking.estimatedPrice?.toString() ?? ""} min="0" name="estimatedPrice" step="0.01" type="number" /></label><label className="form-field">Final price (€)<input defaultValue={booking.finalPrice?.toString() ?? ""} min="0" name="finalPrice" step="0.01" type="number" /></label></div><div className="form-grid two-columns"><label className="form-field">Payment status<select defaultValue={booking.paymentStatus} name="paymentStatus"><option value="UNPAID">Unpaid</option><option value="PAID">Paid</option></select></label><label className="form-field">Payment method<select defaultValue={booking.paymentMethod ?? ""} name="paymentMethod"><option value="">Not selected</option><option value="CASH">Cash</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CARD">Card</option><option value="PAYCONIQ">Payconiq</option><option value="OTHER">Other</option></select></label></div><label className="form-field">Internal notes<textarea defaultValue={booking.internalNotes ?? ""} name="internalNotes" /></label><label className="form-field">Change note<input name="actionNote" placeholder="Why this changed (optional)" /></label><button className="button button-primary" type="submit"><Save aria-hidden="true" size={18} />Save booking</button></form></aside></div>
  </div></AdminShell>;
}
